name: recipe_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Spaghetti_Bolognese.jpg
    - assets/indian-food.jpg
    - assets/pancake.jpg
    - assets/pastry.jpg
    - assets/schnitzel.jpg
    - assets/smoked-salmon.jpg
    - assets/toast.jpg
    - assets/burger.jpg
